title = "Currículo Patty"
nome = "Patrícia Santana"
tel = "(11) 999999999"
endereco = "Rua Que Sobe e Desce, numero que desaparece"
cidade = "São Paulo"
email = "email@email.com"
objetivo = "Analista Senior"
formacao_acad = "Pós-Graduação em Ciências de Dados"
faculdade = "Mackenzie"
ano = "2023"
exp_prof = "Engenheira de Plataforma de dados"
empresa = "Itaú"
desde = "2012"

