from elem import Elem, create_class

Html = create_class('html')
Head = create_class('head')
Body = create_class('body')
Title = create_class('title')
Meta = create_class('meta', single=True)
Img = create_class('img', single=True)
Table = create_class('table')
Th = create_class('th')
Tr = create_class('tr')
Td = create_class('td')
Ul = create_class('ul')
Ol = create_class('ol')
Li = create_class('li')
H1 = create_class('h1')
H2 = create_class('h2')
P = create_class('p')
Div = create_class('div')
Span = create_class('span')
Hr = create_class('hr', single=True)
Br = create_class('br', single=True)
